name: CI Pwa
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 18.
          cache: npm
      - name: 'run install, build'
        run: |
          npm install
          npm install -g @angular/cli
          ng build
